time_lapse_time_homepage:
    path:     /
    defaults: { _controller: TimeLapseTimeBundle:Default:index }
time_lapse_time_enonce:
    path:     /enonce/{id}
    defaults: { _controller: TimeLapseTimeBundle:Default:enonce }
    requirements:
        _method:  POST
time_lapse_time_message:
    path:     /message
    defaults: { _controller: TimeLapseTimeBundle:Default:message }
    requirements:
        _method:  POST
time_lapse_time_merde:
    path:     /rooms/{id}/slots
    defaults: { _controller: TimeLapseTimeBundle:Default:roomslot }
    requirements:
        _method:  GET


